# Generated by Django 5.0.3 on 2024-04-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_subscriptionmodel_is_subscribed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='is_active',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='reference_name',
            field=models.CharField(default='MyBankAccount', max_length=125),
        ),
    ]
