# Generated by Django 5.0.3 on 2024-06-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='category',
            field=models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability')], default='asset', max_length=10),
        ),
    ]
