# Generated by Django 5.0.3 on 2024-04-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_analysis', '0002_rename_keywords_keyword_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
